### ISSUE TITLE
vc - mobile optimization

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/www_venturecreator#11]
just need left right margin on all pages mobile

<img width="303" alt="Screenshot 2023-05-11 at 16 13 31" src="https://github.com/threefoldfoundation/www_venturecreator/assets/43240801/33c7031b-57e1-460a-9856-b222e5867bf6">
<img width="304" alt="Screenshot 2023-05-11 at 16 13 18" src="https://github.com/threefoldfoundation/www_venturecreator/assets/43240801/f9e46518-fb08-4e9d-8c32-28d689c727bd">
<img width="288" alt="Screenshot 2023-05-11 at 16 13 04" src="https://github.com/threefoldfoundation/www_venturecreator/assets/43240801/0c5156ca-8727-4fc5-95d7-8fe5a69e3ff1">
<img width="295" alt="Screenshot 2023-05-11 at 16 12 42" src="https://github.com/threefoldfoundation/www_venturecreator/assets/43240801/88fd5a6d-bb12-4032-839d-f841597a47cf">
<img width="307" alt="Screenshot 2023-05-11 at 16 12 24" src="https://github.com/threefoldfoundation/www_venturecreator/assets/43240801/59c09b66-74fa-402c-9e92-9754833bff78">
<img width="302" alt="Screenshot 2023-05-11 at 16 12 14" src="https://github.com/threefoldfoundation/www_venturecreator/assets/43240801/bf16908e-9d50-4807-82f1-ce46dcb8ae97">

**Comment by ehab-hassan** [comment]
Fixed
![image](https://github.com/threefoldfoundation/www_venturecreator/assets/10484295/e519b1c1-677c-4388-9559-415c9aabc60d)

**Comment by sasha-astiadi** [comment]
venturecreator doesnt have staging., can make one
