### ISSUE TITLE
change website to dark layout

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/www_venturecreator#2]
<img width="1431" alt="Screenshot 2023-01-24 at 17 07 13" src="https://user-images.githubusercontent.com/43240801/214251854-2e85a48e-4bba-42e7-8ad3-f323925b885e.png">

at the moment were building the website venture creator but want to make it dark as default, meaning , background should be black, and the texts should be white. 

- [x] change all bg color css related into black, #000000
- [x] change all texts related css into white #FFFFFF
- [x] make the max width the same like ourphone website
- [x] for the future, create a layout repo, same like www_examplezola but dark mode, name it www_examplezola_dark

**Comment by ehab-hassan** [comment]
done 
https://github.com/threefoldfoundation/www_examplezola_dark
