### ISSUE TITLE
Address Kristof Feedback

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_venturecreator#3]
**General**
- [x] Try the logo for the Venture Creator with the gold token instead (@sasha-astiadi)
- [x] add Favicon (@sasha-astiadi)
- [ ] Enable blogs and newsroom (@sasha-astiadi) ... look at figma file for which ones to add
- [x] Titles of pages should all be at the same height (@sasha-astiadi)

**Homepage**
- [x] Top image in header should be bigger (@samtaggart)
- [x] The image of the two people needs to be changed ... not much direction otherwise (@sasha-astiadi)
- [x] Remove individual ventures, OK to just have ventures button – it's repeated content (@samtaggart)

**Manifesto**
- [x] It's a declaration, not rights. Use book with tree variations on right and left for declaration and laws. Explain digital laws as anyone making technology needs to follow these laws and manifesto is for the users of the technology (@sasha-astiadi and @samtaggart)

**Experience**
- [x] Top-right image needs to be changed (@sasha-astiadi)
- [x] At bottom put different exits (slide) (@sasha-astiadi)
- [x] Change URL to /experience instead of /experiences (@sasha-astiadi)

**Projects**
- [x] Turn each into a template with same info: vision and mission + current status + roadmap (@samtaggart)
- [x] New graphic for OurPhone (@sasha-astiadi)
- [x] Check and current status and roadmap text (@despiegk)

**About**
- [ ] Add people's faces as described in figma (@sasha-astiadi)

**Comment by sasha-astiadi** [comment]
"Titles of pages should all be at the same height"  @samtaggart i dont get this one

**Comment by samtaggart** [comment]
@sasha-astiadi Click between the screens and you will see the title is at a slightly different height on some of the pages. Height as in placement on the screen.

<img width="1436" alt="Screen Shot 2023-01-25 at 6 11 44 PM" src="https://user-images.githubusercontent.com/50134479/214600206-568b2912-0bc9-4fa9-971c-3373db584c63.png">
<img width="1440" alt="Screen Shot 2023-01-25 at 6 11 54 PM" src="https://user-images.githubusercontent.com/50134479/214600224-eacf28bb-8828-4cf4-a7f6-a9786d0c5c41.png">

**Comment by sasha-astiadi** [comment]
only thing is the blog - i will investigate today, and the exits, i forgot again sorry what does exits mean again on this @samtaggart ...

**Comment by samtaggart** [comment]
Old exits is the slide we are talking about right now with Kristof in the chat that show the past exits of Incubaid.

**Comment by sasha-astiadi** [comment]
https://github.com/threefoldfoundation/www_venturecreator/issues/10 new issue, deleting this one
