### ISSUE TITLE
fix responsiveness issue 

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/www_venturecreator#4]
<img width="363" alt="Screenshot 2023-02-02 at 20 57 15" src="https://user-images.githubusercontent.com/43240801/216331118-0b0bd97a-b8c5-4ddc-9723-e4ff89f85fd1.png">

hi ehab, i used inline css to fix the sizes of the headers.... immediately on index.md
because the size of the font that came originally from the template was too big.
now weve got problem because its not really responsive on the mobile version
<img width="314" alt="Screenshot 2023-02-02 at 21 00 40" src="https://user-images.githubusercontent.com/43240801/216331812-267ed16a-42c0-4979-bbec-518db2d9c091.png">

can you please help me:

- put these inline custom size font settings into the template css... and delete the inline after.
- make sure its responsive on mobile

thank you

**Comment by ehab-hassan** [comment]
all pages fixed and responsive

**Comment by sasha-astiadi** [comment]
thank you @ehab-hassan :)
